version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
networks:
  net: